services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - 'ADMIN_NAME=${ADMIN_NAME:-System Administrator}'
      - 'ADMIN_EMAIL=${ADMIN_EMAIL:-admin@biovault.com}'
      - 'ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}'
      - 'MONGODB_DATABASE=${MONGODB_DATABASE:-biovault-db}'
      - 'MONGODB_URI=${MONGODB_URI:-mongodb://root:secret@mongodb:27017}'
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-biovault-db}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD:-secret}'
      - 'MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER:-root}'
    ports:
      - '27017:27017'
