spring.application.name=biovault

spring.security.user.name=${SECURITY_USERNAME:admin}
spring.security.user.password=${SECURITY_PASSWORD:admin123}

spring.mongodb.database=${MONGODB_DATABASE:biovault-db}
spring.mongodb.uri=${MONGODB_URI}