spring.application.name=biovault

spring.security.user.name=${SECURITY_USERNAME:admin}
spring.security.user.password=${SECURITY_PASSWORD:admin123}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/biovault-db}
spring.data.mongodb.database=${MONGODB_DATABASE:biovault-db}

server.port=8080

# If you have JPA dependencies, uncomment the line below:
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration